<a href="https://colab.research.google.com/github/sr606/LinkedIn-Data-Mining-Analysis/blob/main/LinkedIn_Data_Mining_Analyzing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
connections = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Almabetter /EDA/LinkedIn/Connections1.csv')

In [4]:
connections.columns

Index(['First Name', 'Last Name', 'Full Name', 'Company', 'Position',
       'Connected On'],
      dtype='object')

In [5]:
connections.head()

,First Name,Last Name,Full Name,Company,Position,Connected On
0,Shahrukh,Ahmad,Shahrukh Ahmad,Cartesian Consulting,Data Analyst,19-08-2023
1,Vishal,Jagtap,Vishal Jagtap,GlobalLogic India,Software Test Engineer,19-08-2023
2,Rahul,verma,Rahul verma,AlmaBetter,Data Science Trainee,19-08-2023
3,Shweta,Jamdade,Shweta Jamdade,NaN,NaN,19-08-2023
4,sakshi,sawant,sakshi sawant,pursuing B.tech,Fresher,19-08-2023

In [6]:
connections.isna()

     First Name  Last Name  Full Name  Company  Position  Connected On
0         False      False      False    False     False         False
1         False      False      False    False     False         False
2         False      False      False    False     False         False
3         False      False      False     True      True         False
4         False      False      False    False     False         False
..          ...        ...        ...      ...       ...           ...
614       False      False      False    False     False         False
615       False      False      False    False     False         False
616       False      False      False    False     False         False
617       False      False      False     True      True         False
618       False      False      False     True      True         False

[619 rows x 6 columns]

In [7]:
connections.isna().sum()

First Name        9
Last Name         9
Full Name         0
Company         101
Position        101
Connected On      0
dtype: int64

In [8]:
connections.shape

(619, 6)

In [9]:
connections.info

<bound method DataFrame.info of     First Name Last Name        Full Name                         Company  \
0     Shahrukh     Ahmad   Shahrukh Ahmad            Cartesian Consulting
1       Vishal    Jagtap    Vishal Jagtap               GlobalLogic India
2        Rahul     verma      Rahul verma                      AlmaBetter
3       Shweta   Jamdade   Shweta Jamdade                             NaN
4       sakshi    sawant    sakshi sawant                 pursuing B.tech
..         ...       ...              ...                             ...
614    Vaibhav   Bhosale  Vaibhav Bhosale  LTI - Larsen & Toubro Infotech
615     Rasika   Upadhye   Rasika Upadhye              Persistent Systems
616     Aditya     Yadav     Aditya Yadav                 Akruti solution
617      Rohan   Dingane    Rohan Dingane                             NaN
618   Satyajit    Chavan  Satyajit Chavan                             NaN

                   Position Connected On
0              Data Analyst   19-08-2023
1    Software Test Engineer   19-08-2023
2      Data Science Trainee   19-08-2023
3                       NaN   19-08-2023
4                   Fresher   19-08-2023
..                      ...          ...
614       Senior Specialist    19-Mar-19
615  Lead Software Engineer    14-Mar-19
616                 Founder    12-Mar-19
617                     NaN    10-Mar-19
618                     NaN    08-Mar-19

[619 rows x 6 columns]>

In [10]:
connections.dropna(inplace = True)

In [11]:
connections.shape

(518, 6)

In [12]:
connections.isna().sum()

First Name      0
Last Name       0
Full Name       0
Company         0
Position        0
Connected On    0
dtype: int64

In [13]:
invitations = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Almabetter /EDA/LinkedIn/Invitations.csv')

In [14]:
invitations.columns

Index(['From', 'To', 'Sent At', 'Message', 'Direction', 'inviterProfileUrn',
       'inviteeProfileUrn'],
      dtype='object')

In [15]:
invitations.shape

(224, 7)

In [16]:
invitations.head(20)

,From,To,Sent At,Message,Direction,inviterProfileUrn,inviteeProfileUrn
0,Shraddha Chavan,Prasad Wagh,"8/15/23, 1:53 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:536059636
1,Shraddha Chavan,Shraddha Chandurkar,"8/15/23, 1:44 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:908658717
2,Shraddha Chavan,Ajay Sable,"8/15/23, 1:37 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:1016351361
3,Shraddha Chavan,Dipanshu kumar,"8/15/23, 1:28 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:784838207
4,Shraddha Chavan,Ashalata Barada,"8/14/23, 7:19 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:1106288875
5,Shraddha Chavan,Siddhi Thorat,"8/14/23, 7:16 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:1157973962
6,Shraddha Chavan,Vibhuti Gupta,"8/14/23, 7:14 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:974250037
7,Shraddha Chavan,Shyam S,"8/11/23, 9:30 PM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:206706591
8,Shraddha Chavan,Manisha Dhanuka,"8/6/23, 1:21 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:606975107
9,Shraddha Chavan,Akshay Pawar,"8/6/23, 1:20 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:1062537522
10,Shraddha Chavan,Kaustubh Amare,"8/6/23, 1:17 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:813000042
11,Shraddha Chavan,Charan Shivaram,"8/6/23, 1:16 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:973378383
12,Shraddha Chavan,Rahul Gupta,"7/29/23, 7:28 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:774433327
13,Shraddha Chavan,Nivya T,"7/29/23, 7:22 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:883691426
14,Shraddha Chavan,Sanjay Jaiswal,"7/29/23, 7:18 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:483090511
15,Shraddha Chavan,Sandipan Das,"7/29/23, 7:16 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:709039297
16,Shraddha Chavan,Karan Rawat,"7/29/23, 7:15 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:763389452
17,Shraddha Chavan,Bapu B,"7/29/23, 7:14 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:1007810615
18,Shraddha Chavan,Vishwajeet sutar,"7/27/23, 5:08 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:944319169
19,Shraddha Chavan,Vivek CP,"7/26/23, 4:46 AM",NaN,OUTGOING,urn:li:member:666792457,urn:li:member:664985573

In [17]:
invitations.isna().sum()

From                   0
To                     0
Sent At                0
Message              221
Direction              0
inviterProfileUrn      0
inviteeProfileUrn      0
dtype: int64

In [18]:
invitations[invitations['Message'].notnull()].head()

,From,To,Sent At,Message,Direction,inviterProfileUrn,inviteeProfileUrn
184,Ajith Pushparaj,Shraddha Chavan,"5/11/23, 9:30 PM","Greetings Shraddha , I noticed we share an int...",INCOMING,urn:li:member:893018748,urn:li:member:666792457
196,Aiman Jamadar,Shraddha Chavan,"5/4/23, 11:24 AM",hi,INCOMING,urn:li:member:698675030,urn:li:member:666792457
206,Sam Andhorikar,Shraddha Chavan,"4/22/23, 9:37 PM","Hey guys, i'm looking for some good leaders w...",INCOMING,urn:li:member:950983502,urn:li:member:666792457

In [19]:
invitations.shape

(224, 7)

In [20]:
invitations = invitations[invitations['Direction'] == 'INCOMING']

In [21]:
invitations.shape

(137, 7)

In [22]:
np.unique(invitations['Direction'])

array(['INCOMING'], dtype=object)

In [23]:
invitations['Company'] = ''
invitations.head()

<ipython-input-23-a53b075b8bb9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invitations['Company'] = ''

,From,To,Sent At,Message,Direction,inviterProfileUrn,inviteeProfileUrn,Company
87,Aditya Karve,Shraddha Chavan,"8/20/23, 5:44 AM",NaN,INCOMING,urn:li:member:996718690,urn:li:member:666792457,
88,Brinly Dot,Shraddha Chavan,"8/18/23, 10:26 AM",NaN,INCOMING,urn:li:member:1172525693,urn:li:member:666792457,
89,Akash Bhor,Shraddha Chavan,"8/18/23, 5:32 AM",NaN,INCOMING,urn:li:member:601433786,urn:li:member:666792457,
90,Rutvik Patil,Shraddha Chavan,"8/17/23, 8:36 AM",NaN,INCOMING,urn:li:member:1034256430,urn:li:member:666792457,
91,Suraj Kumar,Shraddha Chavan,"8/17/23, 12:56 AM",NaN,INCOMING,urn:li:member:869018630,urn:li:member:666792457,

In [24]:
connections[connections['Full Name'] == 'Vishal Jagtap']['Company'].values[0]

'GlobalLogic India'

In [25]:
len(invitations)

137

In [26]:
invitations = invitations.reset_index(drop = True)
invitations

,From,To,Sent At,Message,Direction,inviterProfileUrn,inviteeProfileUrn,Company
0,Aditya Karve,Shraddha Chavan,"8/20/23, 5:44 AM",NaN,INCOMING,urn:li:member:996718690,urn:li:member:666792457,
1,Brinly Dot,Shraddha Chavan,"8/18/23, 10:26 AM",NaN,INCOMING,urn:li:member:1172525693,urn:li:member:666792457,
2,Akash Bhor,Shraddha Chavan,"8/18/23, 5:32 AM",NaN,INCOMING,urn:li:member:601433786,urn:li:member:666792457,
3,Rutvik Patil,Shraddha Chavan,"8/17/23, 8:36 AM",NaN,INCOMING,urn:li:member:1034256430,urn:li:member:666792457,
4,Suraj Kumar,Shraddha Chavan,"8/17/23, 12:56 AM",NaN,INCOMING,urn:li:member:869018630,urn:li:member:666792457,
...,...,...,...,...,...,...,...,...
132,Arpit Rastogi,Shraddha Chavan,"2/26/23, 10:32 PM",NaN,INCOMING,urn:li:member:816295276,urn:li:member:666792457,
133,Girish P S Rao,Shraddha Chavan,"2/26/23, 11:21 AM",NaN,INCOMING,urn:li:member:257416721,urn:li:member:666792457,
134,Samruddhi Bakare,Shraddha Chavan,"2/26/23, 2:28 AM",NaN,INCOMING,urn:li:member:959959916,urn:li:member:666792457,
135,Vishwas Kshirsagar,Shraddha Chavan,"2/26/23, 12:10 AM",NaN,INCOMING,urn:li:member:980270404,urn:li:member:666792457,
136,Prashant Nalawade,Shraddha Chavan,"2/23/23, 8:31 PM",NaN,INCOMING,urn:li:member:87751169,urn:li:member:666792457,

In [27]:
for i in range(0, len(invitations)):
  #print(i, invitations['From'][i])
  try:
    company = connections[connections['Full Name'] == invitations['From'][i]]['Company'].values[0]
    #print(company)
    invitations['Company'][i] = company
  except:
    continue

In [28]:
invitations

,From,To,Sent At,Message,Direction,inviterProfileUrn,inviteeProfileUrn,Company
0,Aditya Karve,Shraddha Chavan,"8/20/23, 5:44 AM",NaN,INCOMING,urn:li:member:996718690,urn:li:member:666792457,
1,Brinly Dot,Shraddha Chavan,"8/18/23, 10:26 AM",NaN,INCOMING,urn:li:member:1172525693,urn:li:member:666792457,Åbo Akademi University
2,Akash Bhor,Shraddha Chavan,"8/18/23, 5:32 AM",NaN,INCOMING,urn:li:member:601433786,urn:li:member:666792457,Clarion Technologies
3,Rutvik Patil,Shraddha Chavan,"8/17/23, 8:36 AM",NaN,INCOMING,urn:li:member:1034256430,urn:li:member:666792457,Kalammawadi Wildlife Tourism pvt. Ltd
4,Suraj Kumar,Shraddha Chavan,"8/17/23, 12:56 AM",NaN,INCOMING,urn:li:member:869018630,urn:li:member:666792457,Citizens Alliance
...,...,...,...,...,...,...,...,...
132,Arpit Rastogi,Shraddha Chavan,"2/26/23, 10:32 PM",NaN,INCOMING,urn:li:member:816295276,urn:li:member:666792457,
133,Girish P S Rao,Shraddha Chavan,"2/26/23, 11:21 AM",NaN,INCOMING,urn:li:member:257416721,urn:li:member:666792457,Ceplas Industrial
134,Samruddhi Bakare,Shraddha Chavan,"2/26/23, 2:28 AM",NaN,INCOMING,urn:li:member:959959916,urn:li:member:666792457,
135,Vishwas Kshirsagar,Shraddha Chavan,"2/26/23, 12:10 AM",NaN,INCOMING,urn:li:member:980270404,urn:li:member:666792457,topmate.io
136,Prashant Nalawade,Shraddha Chavan,"2/23/23, 8:31 PM",NaN,INCOMING,urn:li:member:87751169,urn:li:member:666792457,Bajaj Electricals Ltd - T&D

In [29]:
invitations.drop(labels=['Message','Direction'], axis = 1, inplace = True)
invitations

,From,To,Sent At,inviterProfileUrn,inviteeProfileUrn,Company
0,Aditya Karve,Shraddha Chavan,"8/20/23, 5:44 AM",urn:li:member:996718690,urn:li:member:666792457,
1,Brinly Dot,Shraddha Chavan,"8/18/23, 10:26 AM",urn:li:member:1172525693,urn:li:member:666792457,Åbo Akademi University
2,Akash Bhor,Shraddha Chavan,"8/18/23, 5:32 AM",urn:li:member:601433786,urn:li:member:666792457,Clarion Technologies
3,Rutvik Patil,Shraddha Chavan,"8/17/23, 8:36 AM",urn:li:member:1034256430,urn:li:member:666792457,Kalammawadi Wildlife Tourism pvt. Ltd
4,Suraj Kumar,Shraddha Chavan,"8/17/23, 12:56 AM",urn:li:member:869018630,urn:li:member:666792457,Citizens Alliance
...,...,...,...,...,...,...
132,Arpit Rastogi,Shraddha Chavan,"2/26/23, 10:32 PM",urn:li:member:816295276,urn:li:member:666792457,
133,Girish P S Rao,Shraddha Chavan,"2/26/23, 11:21 AM",urn:li:member:257416721,urn:li:member:666792457,Ceplas Industrial
134,Samruddhi Bakare,Shraddha Chavan,"2/26/23, 2:28 AM",urn:li:member:959959916,urn:li:member:666792457,
135,Vishwas Kshirsagar,Shraddha Chavan,"2/26/23, 12:10 AM",urn:li:member:980270404,urn:li:member:666792457,topmate.io
136,Prashant Nalawade,Shraddha Chavan,"2/23/23, 8:31 PM",urn:li:member:87751169,urn:li:member:666792457,Bajaj Electricals Ltd - T&D

In [30]:
invitations.drop(labels=['From','To','Sent At'], axis = 1, inplace = True)
invitations

,inviterProfileUrn,inviteeProfileUrn,Company
0,urn:li:member:996718690,urn:li:member:666792457,
1,urn:li:member:1172525693,urn:li:member:666792457,Åbo Akademi University
2,urn:li:member:601433786,urn:li:member:666792457,Clarion Technologies
3,urn:li:member:1034256430,urn:li:member:666792457,Kalammawadi Wildlife Tourism pvt. Ltd
4,urn:li:member:869018630,urn:li:member:666792457,Citizens Alliance
...,...,...,...
132,urn:li:member:816295276,urn:li:member:666792457,
133,urn:li:member:257416721,urn:li:member:666792457,Ceplas Industrial
134,urn:li:member:959959916,urn:li:member:666792457,
135,urn:li:member:980270404,urn:li:member:666792457,topmate.io
136,urn:li:member:87751169,urn:li:member:666792457,Bajaj Electricals Ltd - T&D

In [31]:
invitations.drop(labels=['inviterProfileUrn','inviteeProfileUrn'],axis = 1, inplace = True)
invitations

                                   Company
0
1                   Åbo Akademi University
2                     Clarion Technologies
3    Kalammawadi Wildlife Tourism pvt. Ltd
4                        Citizens Alliance
..                                     ...
132
133                      Ceplas Industrial
134
135                             topmate.io
136            Bajaj Electricals Ltd - T&D

[137 rows x 1 columns]

In [32]:
invitations.to_csv('invitations.csv')

#**Generating Fake data**

In [33]:
connections.columns

Index(['First Name', 'Last Name', 'Full Name', 'Company', 'Position',
       'Connected On'],
      dtype='object')

In [34]:
connections.drop(labels = ['First Name','Last Name','Full Name'], axis = 1, inplace = True)
connections

                            Company                      Position Connected On
0              Cartesian Consulting                  Data Analyst   19-08-2023
1                 GlobalLogic India        Software Test Engineer   19-08-2023
2                        AlmaBetter          Data Science Trainee   19-08-2023
4                   pursuing B.tech                       Fresher   19-08-2023
5                 Citizens Alliance  Data Analytics and Scientist   19-08-2023
..                              ...                           ...          ...
612      Cooper Corporation Pvt Ltd                Engineer-R & D    06-Apr-19
613                   Digital Beats                 Founder & CEO    19-Mar-19
614  LTI - Larsen & Toubro Infotech             Senior Specialist    19-Mar-19
615              Persistent Systems        Lead Software Engineer    14-Mar-19
616                 Akruti solution                       Founder    12-Mar-19

[518 rows x 3 columns]

In [35]:
!pip install faker

Collecting faker
  Downloading Faker-19.3.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-19.3.1

In [36]:
from faker import Faker

In [37]:
fake = Faker()

In [38]:
fake.name()

'James Martinez'

In [39]:
connections['Full Name'] = ''
connections

,Company,Position,Connected On,Full Name
0,Cartesian Consulting,Data Analyst,19-08-2023,
1,GlobalLogic India,Software Test Engineer,19-08-2023,
2,AlmaBetter,Data Science Trainee,19-08-2023,
4,pursuing B.tech,Fresher,19-08-2023,
5,Citizens Alliance,Data Analytics and Scientist,19-08-2023,
...,...,...,...,...
612,Cooper Corporation Pvt Ltd,Engineer-R & D,06-Apr-19,
613,Digital Beats,Founder & CEO,19-Mar-19,
614,LTI - Larsen & Toubro Infotech,Senior Specialist,19-Mar-19,
615,Persistent Systems,Lead Software Engineer,14-Mar-19,
616,Akruti solution,Founder,12-Mar-19,

In [40]:
connections = connections.reset_index(drop = True)

In [41]:
for i in range(0, len(connections)):
  connections['Full Name'][i] = fake.name()

In [42]:
connections

,Company,Position,Connected On,Full Name
0,Cartesian Consulting,Data Analyst,19-08-2023,Jennifer Shah
1,GlobalLogic India,Software Test Engineer,19-08-2023,Mrs. Megan Baird
2,AlmaBetter,Data Science Trainee,19-08-2023,Michelle Rose
3,pursuing B.tech,Fresher,19-08-2023,Jeff Rodriguez
4,Citizens Alliance,Data Analytics and Scientist,19-08-2023,Michelle Palmer
...,...,...,...,...
513,Cooper Corporation Pvt Ltd,Engineer-R & D,06-Apr-19,Michael Armstrong
514,Digital Beats,Founder & CEO,19-Mar-19,Julie Banks
515,LTI - Larsen & Toubro Infotech,Senior Specialist,19-Mar-19,Daniel Rojas
516,Persistent Systems,Lead Software Engineer,14-Mar-19,Richard Crane
517,Akruti solution,Founder,12-Mar-19,Sean Pham

In [43]:
connections.to_csv('connections.csv')

#Messages

In [44]:
messages = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Almabetter /EDA/LinkedIn/messages.csv')

In [45]:
messages.columns

Index(['CONVERSATION ID', 'CONVERSATION TITLE', 'FROM', 'SENDER PROFILE URL',
       'TO', 'RECIPIENT PROFILE URLS', 'DATE', 'SUBJECT', 'CONTENT', 'FOLDER'],
      dtype='object')

In [46]:
messages.shape

(2346, 10)

In [47]:
messages.head(1)

,CONVERSATION ID,CONVERSATION TITLE,FROM,SENDER PROFILE URL,TO,RECIPIENT PROFILE URLS,DATE,SUBJECT,CONTENT,FOLDER
0,2-ZDE0ZWJhODMtOGQ5MC00ZTgzLWJlMWMtNjUzNzQyNTk0...,NaN,Satyajit Chavan,https://www.linkedin.com/in/satyajit-chavan-20...,Shraddha Chavan,https://www.linkedin.com/in/shraddhachavan9,2023-08-23 15:18:59 UTC,NaN,NaN,INBOX

In [48]:
messages = messages['CONTENT']
messages

0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...
2341    Hi %FIRSTNAME%,Based on your recent activity, ...
2342    Hi Shraddha,Based on your recent activity, I’d...
2343    Hi Shraddha,Based on your recent activity, I&r...
2344    I am Varadraj Nikam , a Financial Planner/ Adv...
2345    Hi,  I would like to personally invite you to ...
Name: CONTENT, Length: 2346, dtype: object

In [49]:
messages.isna().sum()

179

In [50]:
messages.dropna(inplace = True)
messages.shape

(2167,)

In [51]:
messages.to_csv('messages.csv')